# Generated by Django 5.0.4 on 2024-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='unit',
            field=models.CharField(choices=[('kWh', 'Kilowatt Hour'), ('MWh', 'Megawatt Hour'), ('GJ', 'Gigajoule')], max_length=3),
        ),
    ]
