apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ui-gateway
  namespace: shared
spec:
  selector:
    istio: ingressgateway # Use Istio's built-in ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
